### PR TITLE
Pulled upstream changes to add S3 owner translation settings for repl…

### PR DESCRIPTION
**Pull request by mschroering**
…ication

### CODE REVIEW

**Comment by mdlavin** [comment]
Changes look good to me. Did you run the S3 test suite?

**Comment by mschroering** [comment]
This is where I'm going to need some help.  I tried to do a `make test` and get a bunch of errors.   What is the recommended way to do this?

**Comment by philidem** [comment]
I cloned this project and to `$GOPATH/src/github.com/terraform-providers/terraform-provider-aws` and then ran `make build` and `make test` and they both succeeded. Not sure why you are seeing errors.

**Review by anthonyroach — APPROVED** [review]

**Comment by philidem** [comment]
@mschroering it looks like you didn't branch off the branch that had @mdlavin's patches. I think you should create your branch off of `v1.14.0_patched` and then rebase that on `v1.19.0` (the latest release).

**Comment by mschroering** [comment]
Closing out this PR for new one on the proper branch.

**Pull request closed without merging**
